---

- name: Clone mikrotik-backup from github
  git: https://github.com/vaizard/mikrotik-backup dest={{ mikrotik_backup_path }} version={{ mikrotik_backup_version }}

- name: Ensure mikrotik-backup's openssh config is set.
  template:
    src: ssh_config.j2
    dest: "{{ mikrotik_backup_ssh_config_path }}"

- name: Ensure that mikrotik-backup's host list is configured
  template:
    src: host-list.j2
    dest: "{{ mikrotik_backup_path }}/host-list"

- name: Ensure cron backup jobs are configured
  cron:
    name: "Mikrotik backups"
    minute:  "{{ mikrotik_backup_cron_minute }}"
    hour:  "{{ mikrotik_backup_cron_hour }}"
    weekday: "{{ mikrotik_backup_cron_weekday }}"
    job: "ls -alh > /dev/null"
  
  
